cli:
  plugins:
    pycoverage:
      report_type: json
flag_management:
  individual_flags:
  - carryforward: true
    carryforward_mode: labels
    name: smart-tests
    statuses:
    - type: project
    - type: patch
