version: 2.1
orbs:
  codecov: codecov/codecov@4

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests and collect coverage
          command: |
            cd tests
            pytest --cov app
      - codecov/upload
      - store_test_results:
          path: tests/results  # Path where test results are located

workflows:
  version: 2.1
  build-test:
    jobs:
      - build
