version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest tests/ --cov app
      - run:
          name: Upload coverage to Codecov
          command: codecov/upload

workflows:
  version: 2.1
  build-test:
    jobs:
      - build
